name: publish-pact-ef-packages
run-name: "[PUBLISH] ${{ inputs.project }} - ${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Select a project to publish'
        required: true
        type: choice
        options:
          - PactEf.Capture
          - PactEf.Verify
      version:
        description: 'Version to publish (e.g. 1.0.0 or 1.0.0-beta1)'
        type: string
        required: true

jobs:
  publish:
    timeout-minutes: 30
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: NuGet login
        uses: Nuget/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Pack Selected Project
        run: |
          TARGET="src/${{ inputs.project }}/${{ inputs.project }}.csproj"
          dotnet pack $TARGET -c Release -o ./artifacts /p:Version=${{ inputs.version }}

      - name: Push to NuGet
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{steps.login.outputs.NUGET_API_KEY}} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate